### PR TITLE
Pull commits from the main fork

### PR DESCRIPTION
**Pull request by Kikasuru**
## Description
Not exactly sure if it'll clash with any of the Touhoumon additions, but there's been a lot of additions in the decomp which could be useful if brought here.

## **Discord contact info**

Kikasuru#2703

### CODE REVIEW

**Comment by Kikasuru** [comment]
Just realized it has some conflicts, shoot.

**Comment by Kikasuru** [comment]
nvm, don't want to deal with you

**Comment by Fatih120** [comment]
next time read the last updated commit, the state of the project, and the state of my server before both pestering people on my server and kicking up dust as you've always done

**Comment by Kikasuru** [comment]
> next time read the last updated commit, the state of the project, and the state of my server before both pestering people on my server and kicking up dust as you've always done

>was asking an honest question
>asked the wrong person because i was confused on who to ask in your server
>commemorated your work on the project
>still berated by the shit person you are

shouldn't have even tried to talk to your shitty ass in the first place

**Pull request closed without merging**
